SENDGRID_PASSWORD: fsjrzrf2
SENDGRID_USERNAME: app26843429@heroku.com
DEVISE_SECRET_KEY: b94fa981ce157f75635f8721acb541e6fd1a778951bf32b56ee1201789e23790c2c989ab16a8c48bb0f7ecbf7c418530081c231fcf20ffbf87e3a41d25cb6c70
AWS_ACCESS_KEY_ID: AKIAIL2Z67IGRHM5HDAA
AWS_SECRET_ACCESS_KEY: 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
development:
	AWS_BUCKET: spencer-cheng-bloccit-development
production:
	AWS_BUCKET: spencer-cheng-bloccit-production
